// File generated by FlutterFire configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration for the supported app platforms.
///
/// The values are project identifiers generated by Firebase/FlutterFire. They
/// are safe to ship in the client app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuA7JEJFnucIRz4GLUtoPw0cPd6hsOZo',
    appId: '1:5685734036:android:4de8408743acc6be0c2281',
    messagingSenderId: '5685734036',
    projectId: 'flex-diet-3aee3',
    storageBucket: 'flex-diet-3aee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgDRuSejsu5OYH3K_ElDrWDbhi13HnO0',
    appId: '1:5685734036:ios:35c1768b87c9480e0c2281',
    messagingSenderId: '5685734036',
    projectId: 'flex-diet-3aee3',
    storageBucket: 'flex-diet-3aee3.firebasestorage.app',
    iosBundleId: 'com.flex.diet.ai',
  );
}
